title: Dekorate
email: dekorateio@gmail.com
url: "https://dekorate.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dekorateio <200f>
github_username:  dekorateio
github_fork_url: "https://github.com/dekorateio/dekorate"
docsurl: "/dekorate"
plugins:
  - jekyll-remote-theme
remote_theme: https://github.com/rhmwes/community-theme
